# Generated by Django 4.2.14 on 2025-03-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_name_category_category_name_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='prod_name',
        ),
    ]
